In [9]:
try:
    result = 6 / 1
    print("Successfully calculated.")
except Exception as e:
    # Handle the exception and try running different code
    print("Cannot divide by zero.")

print("=== === ===")

try:
    result = 6 / 0
    print("Successfully calculated.")
except Exception as e:
    # Handle the exception and try running different code
    print("Cannot divide by zero.")

Successfully calculated.
=== === ===
Cannot divide by zero.


In [15]:
import torch
import torch.nn as nn

class NonNegLoss(nn.Module):
    def __init__(self):
        super(NonNegLoss, self).__init__()

    def forward(self, tensor):
        return torch.sum(torch.relu(-tensor))

# Create a sample tensor (replace this with your actual tensor)
sample_tensor = torch.tensor([[-1, 2, -3, 4, -5]], dtype=torch.float32, requires_grad=True)

# Create an instance of NonNegLoss
non_neg_loss = NonNegLoss()

# Calculate the non-negativity loss
loss = non_neg_loss(sample_tensor)
print("Loss:")
print(loss)

# Backpropagation to compute gradients
loss.backward()

# Check the gradients of the tensor (gradients should be updated after backward)
print("Gradients of the tensor after backward:")
print(sample_tensor.grad)


Loss:
tensor(9., grad_fn=<SumBackward0>)
Gradients of the tensor after backward:
tensor([[-1., -0., -1., -0., -1.]])


In [14]:
a = 1 + \
    2 + \
    3
print(a)

6


In [11]:
import copy
import numpy as np

x = np.array([[1], [2], [3]])
# x = [[1], [2], [3]]

# Create a shallow copy of x
y = copy.deepcopy(x)
y = x.copy()

# Modify the shallow copy
y[0][0] = 4

# Print the original object and the shallow copy
print(x)
print(y)

[[1]
 [2]
 [3]]
[[4]
 [2]
 [3]]


In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Example usage
x_values = np.array([-2, -1, 0, 1, -1.18445])
sigmoid_values = sigmoid(x_values)

print(sigmoid_values)


[0.11920292 0.26894142 0.5        0.73105858 0.23425302]


In [3]:
np.repeat(np.arange(0, 360, 45), 1)

array([  0,  45,  90, 135, 180, 225, 270, 315])